#!/usr/bin/env python3
"""
Download Google Fonts woff2 files locally.
Simple approach: parse CSS line by line, no complex regex.
"""
import subprocess, os, re

FONT_DIR = "/Users/kresnikwang/Work/SKAND STUDIO.COM官网/skand website 2026/fonts"
os.makedirs(FONT_DIR, exist_ok=True)

def curl(url):
    r = subprocess.run(["curl","-sL","--max-time","30","-A","Mozilla/5.0",url],
                       capture_output=True, text=True)
    return r.stdout

def download(url, dest):
    subprocess.run(["curl","-sL","--max-time","60","-A","Mozilla/5.0",
                     "-e","https://fonts.googleapis.com/","-o",dest,url], check=True)

def parse_css(css_text):
    """Parse @font-face blocks by scanning lines. Returns list of dicts."""
    faces = []
    current = None
    for line in css_text.splitlines():
        line = line.strip()
        if "@font-face" in line:
            current = {}
        if current is None:
            continue
        if line.startswith("font-family:"):
            m = re.search(r"'([^']+)'", line)
            if m: current["family"] = m.group(1)
        elif line.startswith("font-style:"):
            m = re.search(r":\s*(\w+)", line)
            if m: current["style"] = m.group(1)
        elif line.startswith("font-weight:"):
            m = re.search(r":\s*(\w+)", line)
            if m: current["weight"] = m.group(1)
        elif line.startswith("font-display:"):
            m = re.search(r":\s*(\w+)", line)
            if m: current["display"] = m.group(1)
        elif line.startswith("src:"):
            m = re.search(r"url\(([^)]+)\)\s*format\('([^']+)'\)", line)
            if m:
                current["url"] = m.group(1)
                current["format"] = m.group(2)
        elif line.startswith("unicode-range:"):
            m = re.search(r":\s*([^;]+)", line)
            if m: current["range"] = m.group(1).strip()
        if line == "}":
            if current and "url" in current:
                current["filename"] = current["url"].split("/")[-1]
                faces.append(current)
            current = None
    return faces

def download_faces(faces):
    downloaded = {}
    for face in faces:
        url = face["url"]
        if url in downloaded:
            face["local"] = downloaded[url]
            continue
        fname = face["filename"]
        dest = os.path.join(FONT_DIR, fname)
        if os.path.exists(dest):
            print(f"  Exists: {fname}")
            downloaded[url] = fname
            face["local"] = fname
            continue
        print(f"  Downloading: {fname} ...")
        try:
            download(url, dest)
            downloaded[url] = fname
            face["local"] = fname
            print(f"    OK ({os.path.getsize(dest)} bytes)")
        except Exception as e:
            print(f"    FAILED: {e}")
    return downloaded

def gen_css(faces):
    lines = ["/* Local Google Fonts - generated by download-fonts.py */", ""]
    seen = set()
    for face in faces:
        key = (face.get("family"), face.get("style"), face.get("weight"), face.get("range"))
        if key in seen:
            continue
        seen.add(key)
        lines.append("@font-face {")
        lines.append(f"  font-family: '{face['family']}';")
        lines.append(f"  font-style: {face['style']};")
        lines.append(f"  font-weight: {face['weight']};")
        if "display" in face:
            lines.append(f"  font-display: {face['display']};")
        lines.append(f"  src: url(fonts/{face['local']}) format('{face['format']}');")
        if "range" in face:
            lines.append(f"  unicode-range: {face['range']};")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)

# --- main ---
print("=== Cormorant Garamond ===")
css_cg = curl("https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600&display=swap")
faces_cg = parse_css(css_cg)
print(f"  Found {len(faces_cg)} @font-face blocks")
download_faces(faces_cg)

print("\n=== Outfit ===")
css_of = curl("https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap")
faces_of = parse_css(css_of)
print(f"  Found {len(faces_of)} @font-face blocks")
download_faces(faces_of)

print("\n=== Generating local-fonts.css ===")
css_out = gen_css(faces_cg + faces_of)
css_path = os.path.join(FONT_DIR, "local-fonts.css")
with open(css_path, "w") as f:
    f.write(css_out)
print(f"  Saved to: {css_path}")
print("\nDone!")
